server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/pipalwaanand27/confsvr
          searchPaths: licensingservice
          username: native-cloud-apps
          password: 0ffended


#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: "file:///E:/confsvr/src/main/resources/config/licensingservice"