server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "file:///E:/confsvr/src/main/resources/config/licensingservice"

